### ISSUE TITLE
Installation TFU001 on Windows CE

### ISSUE THREAD

**Issue by GuevaraDev** [fbarresi/BeckhoffHttpClient#1]
Hi, im trying to use this extension with the JSON extension as well in order to send data to the POWER BI API via a POST, could you explain how is the TFU001 supposed to installed, I'm not really sure how to install the extension.

Thanks

**Comment by fbarresi** [comment]
Hi! If you execute the msi (TFU001_BeckhoffHttpClient.msi) on your target system, the function will be installed.
You can verify the installation looking under the following path on your target system: <i>C:\TwinCAT\Functions\Unofficial\BeckhoffHttpClient\ </i>

**Comment by GuevaraDev** [comment]
I try to install the .msi but The PLC wont open it, I'm using a CX9020 with CE7

![image](https://user-images.githubusercontent.com/20729493/64130651-4b5b5080-cd89-11e9-9baa-4a27698d9574.png)

**Comment by fbarresi** [comment]
Oh! I'm really sorry, but the installer actually does not support Windows CE.
I'm not a specialist with windows CE, but I suppose that if you can install the required .net Framework (4.6.2) on your target you could manually place the function files in the right path for your target.

The Software is compiled as a single exe file, so you can install the TFU001_BeckhoffHttpClient.msi on your pc and then copy the whole directory `C:\TwinCAT\Functions\Unofficial\BeckhoffHttpClient\` to your target plc under the same path.

**Comment by GuevaraDev** [comment]
What file do i need to install manually the .msi file, for some reason i doesn't install on my system (laptop windows 10 64bits) I have installed .net framework 4.6.2 bu tthe installer wont open or create the directory you told me

**Comment by fbarresi** [comment]
Ok, I got you!
1. I realized that the installer had a problem that I have now fixed it. 
this is the latest version https://github.com/fbarresi/BeckhoffHttpClient/releases/tag/1.0.12

2. Sadly you cannot run the software under windows CE, because it have to be compiled for .Net 3.5 Compact Framework. Since none of the dependencies used support it the software cannot also be ported to Windows CE

I really regret, but you should use another plc that supports Windows 7 or Windows 10.
The software was tested with a CX51xx and CX20xx both with windows 10.
