### ISSUE TITLE
Content-Length

### ISSUE THREAD

**Issue by j-pee** [fbarresi/BeckhoffHttpClient#20]
When posting with your software, the Content-Length is larger then the actual size of the body. 
When the messages is bigger the diffirence also increased. 

wrong 

![image](https://github.com/user-attachments/assets/c8f0ab4c-15e4-42d7-b2e0-616bf8f02cce)

good

![image](https://github.com/user-attachments/assets/cd629209-070f-4b5e-be6f-5b7c75bcf85a)

**Comment by fbarresi** [comment]
Hi!

Thank you for reporting this.

Actually, this is just a matter of content indentation.

For this project I will not fix it due to the - following reasons:
- it is a very small overhead that doesn't produce any issue
- it actually leads to more readable requests

As you can see from the user agent, the content of the request is generated using the library RestSharp. You might try to raise an issue to the RestSharp team and ask about that.

Best regards,
FB
